### ISSUE TITLE
This doesn't even compress or encode anything.

### ISSUE THREAD

**Issue by Finxx1** [MortyHub/CZ-File-Encoder#1]
By looking at the compile and de-compile functions, all it does is just rename .zip to .cz; What is the point?

**Comment by MortyHub** [comment]
sush let me have my moments

**Comment by MortyHub** [comment]
shush*

**Comment by MortyHub** [comment]
i will make it encode eventually

**Comment by Finxx1** [comment]
bruh

**Comment by Finxx1** [comment]
fine, i will do it myself

**Comment by MortyHub** [comment]
> fine, i will do it myself

NOOOO IM GOING TO DO IT

**Comment by MortyHub** [comment]
> fine, i will do it myself

:(

**Comment by Finxx1** [comment]
abuse of power

**Comment by Finxx1** [comment]
i did it lmao
